L=[1,2,-3,40,5]
print(len(L))
print(max(L))
print(min(L))
print(sorted(L))
print(sorted(L,reverse=True))
print(f"Actual List{L}")
print(L.count(40))
print(L.index(-3))
L.reverse()
print(L)
print(f"Actual List{L}")
L.sort()
print(L)
print(f"Actual List{L}")
